name: product-catalog-ci

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Download Go dependencies
        run: cd src/product-catalog && go mod download

      - name: Build
        run: cd src/product-catalog && go build -o product-catalog ./src/product-catalog/main.go

      - name: Unit Tests
        run: cd src/product-catalog && go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          cd src/product-catalog
          golangci-lint run

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./src/product-catalog
          file: ./src/product-catalog/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}

  updatingk8s:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update k8s manifest
        run: |
          sed -i 's|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}|g' kubernetes/productcatalog/deploy.yaml

      - name: Commit and push manifest changes
        run: |
          git config user.name "rohitnalat"
          git config user.email "rohitnalat4418@gmail.com"

          git add kubernetes/productcatalog/deploy.yaml

          git diff --cached --quiet || git commit -m "ci: update product-catalog image tag to ${{ github.run_id }}"

          git push